### ISSUE TITLE
Ubuntu 22.0.4 - AMD 9374F

### ISSUE THREAD

**Issue by boranby** [felix-pb/sleeping_vs_spinning#1]
First of all, thanks for the benchmarks, I found them really useful.

Below you can see my `std` benchmark results on an isolated CPU core and non isolated one. The results are without kernel bypass. However, my results aren't event close to your Ubuntu results. If you don't mind can you explain your Ubuntu run and results?

_isolated CPU core:_
```
[std – mpsc – sleeping]
avg = 5.907µs
mid = 5.8µs
min = 4.86µs
max = 12.249µs

[std – mpsc – spinning]
avg = 4.224µs
mid = 3.89µs
min = 3.089µs
max = 28.39µs

[std – tcp – sleeping]
avg = 24.122µs
mid = 24.031µs
min = 22.42µs
max = 34.235µs

[std – tcp – spinning]
avg = 21.631µs
mid = 21.085µs
min = 19.633µs
max = 66.153µs

[std – udp – sleeping]
avg = 15.951µs
mid = 15.899µs
min = 14.992µs
max = 25.036µs

[std – udp – spinning]
avg = 14.733µs
mid = 14.338µs
min = 12.777µs
max = 49.187µs
```

_not isolated:_
```
[std – mpsc – sleeping]
avg = 9.415µs
mid = 9.25µs
min = 7.17µs
max = 17.349µs

[std – mpsc – spinning]
avg = 668ns
mid = 420ns
min = 290ns
max = 15.449µs

[std – tcp – sleeping]
avg = 27.097µs
mid = 26.87µs
min = 20.337µs
max = 42.813µs

[std – tcp – spinning]
avg = 19.027µs
mid = 18.961µs
min = 12.967µs
max = 33.155µs

[std – udp – sleeping]
avg = 19.228µs
mid = 18.857µs
min = 16.097µs
max = 27.987µs

[std – udp – spinning]
avg = 10.858µs
mid = 10.478µs
min = 9.54µs
max = 21.529µs
```

**Comment by felix-pb** [comment]
The point of this project was to show the _relative_ difference between the "sleeping" vs "spinning" implementations, rather than their absolute numbers. Of course, the absolute numbers will depend on the hardware (CPU, NIC, etc.) and perhaps some configs of the linux kernel. Unfortunately, I worked on this a long time ago and I don't have that information anymore. I'm going to close this issue. Good luck on your journey to shaving microseconds!
